
fetch_weed_service: /urGovernor/fetch_weed_service

# Serial setup
serial_output_service: /urGovernor/serial_output_service
serial_input_service: /urGovernor/serial_input_service
serial_port: /dev/ttyTHS1
serial_baud_rate: 115200
serial_timeout_ms: 250

# Max allowable disappeared frames
max_disappeared_frames: 2

# Min frames to identify the same weed in to be valid
min_valid_frames: 30

# Distance tolerance for tracking between frames (in cm)
distance_tolerance: 3
