# Serial setup
serial_output_service: /urGovernor/serial_output_service
serial_input_service: /urGovernor/serial_input_service
serial_port: /dev/ttyTHS1
serial_baud_rate: 115200
serial_timeout_ms: 200

## MOTOR CONFIG
motor_speed_deg_s: 120
motor_accel_deg_s_s: 60

## TIMING PARAMETERS
# **MAX** Query rate of the controller to make service requests for new weeds [Hz]
controller_overall_rate: 3.0
# If this is true, do continuous update of position
# Maximum time for arm actuation
max_actuation_time_override: 1.0
# Time for end-effector to perform its duties (in seconds)
end_effector_time_s: 0.75
# Minimum difference in angles to update Teensy with
min_update_angle: 1

# Timeout on commands
command_timeout_sec: 10

init_sleep_time: 2.0

# Resting angle of the arms
# System will be set to this angle on startup, and every time to do proper imaging
rest_angle_1: 0
rest_angle_2: 0
rest_angle_3: 0

# Limits of arm operation
# First, check cartesian coordinate limits
cartesian_limit_x_max: 30
cartesian_limit_x_min: -30
cartesian_limit_y_max: 25
cartesian_limit_y_min: -40

# Even if cartesian limits pass, check angle limits
angle_limit: 90

soil_offset: 1.0 # offset of soil (cm)
tool_offset: 9.0 # offset of tool (cm)
